language: node_js
node_js:
- '6'
install:
- npm prune
- npm install --loglevel warn
script:
- npm run test
- npm run bundle
- npm run deploy
env:
  global:
  - ENV_DEPLOY_USER=deployer
  - secure: G7IXuTKGi8ajsI3ak4lhPg11D46Kd/iuVF41+/qhn9pqY5KE2mFnmAmDmjD72/z9ZFfxC88alumt27yWPFUCJLIG8xV7ysueqWCZ88hVYEdxgCAd95F8Q4oqrr7S1OgUKIWvBnDYnzOY3xKsRWvB8PcEMlnwPu9meXMzGGM/u50=
  - secure: DVn7B795kspCWmbeXFJ2GcPA/vgihI4IBpQPQhPmba4l85f3j6hqlD1fllj0t4kBnYrfQ9cSZ096V19X8tHnatVt3Db6DzMXcNT24qcBpqS/VwCcm62W+ouHE36TG50MTqzD7OR/Ni8Cd6FbkUdOOwlmXVyJyTBEWzuA24dndAo=
